function PlotStreamLines(S,P,Plt)

    streamline(stream3(S.x1,S.x2,S.x3,...
                        S.u,S.v,S.w,...
                        Plt.sx,Plt.sy,Plt.sz,...
                        0.1));

end